{
 "title": "Business Uptime Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traffic rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(frontend_http_requests_total{namespace=\"default\"}[5m])) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(rate(frontend_http_errors_total[5m])) \n      / sum(rate(frontend_http_requests_total[5m]))) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(frontend_http_errors_total[5m])) \n/\nsum(rate(frontend_http_requests_total[5m])) \n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, pod) (\n    rate(frontend_http_request_duration_seconds_bucket[5m])\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}