{
 "title": "Resource Efficiency Dashboard",
 "time": { "from": "2025-08-22T02:57:41.315Z", "to": "2025-08-22T14:57:41.315Z" },
 "panels": [
  {
   "title": "CPU Usage per Pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"POD\"}[5m])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Gibits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_usage_bytes{namespace=\"default\", container!=\"POD\"}\n) / (1024*1024*1024)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (\n  container_memory_usage_bytes{job=\"kubelet\", container!=\"POD\", \n  node=~\"gke-secure-gke-clust-primary-node-poo-.*\"}\n)\n/\n1024/1024/1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU  Usage per Node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by (node) (\n  rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container!=\"POD\", \n  node=~\"gke-secure-gke-clust-primary-node-poo-.*\"}[5m])\n)\n/\nsum by (node) (\n  machine_cpu_cores{node=~\"gke-secure-gke-clust-primary-node-poo-.*\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod density per node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"default\", \nnode=~\"gke-secure-gke-clust-primary-node-poo-.*\"}) by (node)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}