apiVersion: batch/v1
kind: Job
metadata:
  name: kube-linter-check
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      # Schedule on a standard (non-gVisor) node pool
      nodeSelector:
        cloud.google.com/gke-nodepool: standard-node-pool
      # Use emptyDir instead of GitRepo
      volumes:
        - name: app
          emptyDir: {}
      # InitContainer clones the Git repo
      initContainers:
        - name: git-clone
          image: alpine/git
          command: ["sh", "-c"]
          args:
            - git clone --depth 1 https://github.com/Ahmedrafat9/Microservices-project /app
          volumeMounts:
            - name: app
              mountPath: /app
      # KubeLinter container runs on the cloned manifests
      containers:
        - name: kube-linter
          image: ghcr.io/stackrox/kube-linter:v0.6.6
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "🚀 Running KubeLinter..."
              kube-linter lint /app/kubernetes-manifests \
              || { echo "❌ Linting failed! Fix issues before deploying."; exit 1; }
          volumeMounts:
            - name: app
              mountPath: /app
